<?php


/**
 *
 * @link https://github.com/JMB-Technology-Limited/OSMaths
 * @license https://raw.github.com/JMB-Technology-Limited/OSMaths/master/LICENSE.md 3-clause BSD
 * @copyright (c) JMB Technology Limited, http://jmbtechnology.co.uk/
 */

require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'JMBTechnologyLimited'.DIRECTORY_SEPARATOR.'OSMaths'.DIRECTORY_SEPARATOR.'Misc.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'JMBTechnologyLimited'.DIRECTORY_SEPARATOR.'OSMaths'.DIRECTORY_SEPARATOR.'Transform.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'JMBTechnologyLimited'.DIRECTORY_SEPARATOR.'OSMaths'.DIRECTORY_SEPARATOR.'Vector.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'JMBTechnologyLimited'.DIRECTORY_SEPARATOR.'OSMaths'.DIRECTORY_SEPARATOR.'Ellipsoid.php';

require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'JMBTechnologyLimited'.DIRECTORY_SEPARATOR.'OSMaths'.DIRECTORY_SEPARATOR.'LatLng.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'JMBTechnologyLimited'.DIRECTORY_SEPARATOR.'OSMaths'.DIRECTORY_SEPARATOR.'LatLngWGS84.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'JMBTechnologyLimited'.DIRECTORY_SEPARATOR.'OSMaths'.DIRECTORY_SEPARATOR.'LatLngOSGB36.php';

require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'JMBTechnologyLimited'.DIRECTORY_SEPARATOR.'OSMaths'.DIRECTORY_SEPARATOR.'Datum.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'JMBTechnologyLimited'.DIRECTORY_SEPARATOR.'OSMaths'.DIRECTORY_SEPARATOR.'DatumWGS84.php';
require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'JMBTechnologyLimited'.DIRECTORY_SEPARATOR.'OSMaths'.DIRECTORY_SEPARATOR.'DatumOSGB36.php';

require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'JMBTechnologyLimited'.DIRECTORY_SEPARATOR.'OSMaths'.DIRECTORY_SEPARATOR.'EastingNorthing.php';

